#!/bin/bash
psql -U postgres -h localhost -c 'create database graph;'


psql -U postgres -h localhost -d graph -c "CREATE TABLE $1(ID CHAR(50)     NOT NULL,DATA           jsonb    NOT NULL);"

echo '

  ___  _   ___  ___ ___ _  _  ___     ___ ___ _    ___
 | _ \/_\ | _ \/ __|_ _| \| |/ __|   | __|_ _| |  | __|
 |  _/ _ \|   /\__ \| || .` | (_ |   | _| | || |__| _|
 |_|/_/ \_\_|_\|___/___|_|\_|\___|   |_| |___|____|___|


'


jq -r '"\"(.id)\"|\(.)"' alledges.json  | psql -U postgres -h localhost  -d graph -c "COPY $1 (id,data) FROM stdin delimiter '|' "

echo '
  ___  ___  ___ _____ ___ ___ ___ ___      ___ ___  __  __ ___ _    ___ _____ ___
 | _ \/ _ \/ __|_   _/ __| _ \ __/ __|    / __/ _ \|  \/  | _ \ |  | __|_   _| __|
 |  _/ (_) \__ \ | || (_ |   / _|\__ \   | (_| (_) | |\/| |  _/ |__| _|  | | | _|
 |_|  \___/|___/ |_| \___|_|_\___|___/    \___\___/|_|  |_|_| |____|___| |_| |___|

'