#!/bin/bash
apt-get -y update
apt-get -y install jq
psql -U postgres -h localhost -c 'create database graph;'


psql -U postgres -h localhost -d graph -c "CREATE TABLE $1(ID CHAR(50) PRIMARY KEY     NOT NULL,DATA           bytea    NOT NULL);"


while read p; 
do
  id=$( echo $p | jq -r '.id' ) 
  binary=$(echo $p |  perl -lpe '$_=unpack"B*"')
  echo "$id | $binary" >> $1
done < "$1.json"



psql -U postgres -h localhost  -d graph -c "COPY $1 FROM '/$1' delimiter '|' CSV HEADER;"
