# Basic provisioning example
- name: Create AWS resources
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
  - name: Create an EC2 instance
    ec2:
      key_name: anisble-ssh-key
      region: ap-southeast-2
      assign_public_ip: yes
      vpc_subnet_id: subnet-9793c0f0
      user_data: "{{ lookup('file', 'user-data.txt') }}"
      group_id: 
        - sg-072191cf99e0c90d4
      instance_type: t2.micro
      image: ami-e0c19f83
      wait: yes
      volumes:
        - device_name: /dev/sda1
          volume_type: gp2
          volume_size: 100
          delete_on_termination: true
      exact_count: <instances>
      count_tag:
         Name: aws-demo6
      instance_tags:
         Name: aws-demo6
    register: ec2