- hosts: digitalocean
  vars: 
    do_token: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          30343932646364666239316632376533626637353364333961303439356362623662393537396632
          6564376630363233363336303534316561303464326564350a313639656333393033366638363136
          66393039616337666435313537363062356536336530353134396232336433366230626436346232
          3639343136386336330a666131653934653932623664663839643235666335363062346365613366
          35616134396136653263643438373130653161633835366631353130326234353161373731383935
          33373738393235353262616632333735613937336135393130343333383263393739616630366233
          64386334353831326464316261373263343737363461303966356231663137656463393735353135
          62313737353133393536
    masterdroplet:
    - droplet-three
    es_major_version: "2.x"
    es_version: "2.2.1"
    es_heap_size: "2g"
    es_cluster_name: "production"

  tasks:

  - name: ensure key exists at DigitalOcean
    digital_ocean: >
      state=present
      command=ssh
      name=my_new_key
      ssh_pub_key={{ lookup('file', '../.ssh/id_rsa.pub') }}
      api_token={{ do_token }}
    register: my_ssh_key


  - name: ensure master droplet exist
    digital_ocean: >
      state=present
      command=droplet
      name={{ item }}
      unique_name=yes
      size_id=8gb
      private_networking=yes
      region_id=sgp1
      image_id=ubuntu-16-04-x64
      ssh_key_ids={{ my_ssh_key.ssh_key.id }}
      api_token={{ do_token }}
    with_items: "{{masterdroplet}}"
    register: droplet_details2

  
  - name: Add new master host to our inventory.
    add_host:
      name: "{{ item }}"
      groups: master
    with_items:
     - "{{ droplet_details2.results|map(attribute='droplet.ip_address')|list }}"

  - name: Add new master host to our private inventory.
    add_host:
      name: "{{ item }}"
      groups: masterPrivate
    with_items:
     - "{{ droplet_details2.results|map(attribute='droplet.private_ip_address')|list }}"


  - debug: 
      msg="IP is{{ item.droplet.ip_address }}"
    with_items:
     - "{{ droplet_details2.results }}"

  - debug: 
      msg="{{ groups['masterPrivate'] }}"

- hosts: master
  remote_user: root
  pre_tasks:
    - name: install python 2
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
  vars: 
    ansible_os_family: "Debian"  
    ansible_distribution: "2.4.1.0"  
    es_scripts: false
    es_templates: false
    ansible_python_interpreter: /usr/bin/python3
    es_version_lock: false
    es_heap_size: 1g
    es_api_port: 9201
  roles:
    - { role: elasticsearch, es_instance_name: "node1", es_data_dirs: "/opt/elasticsearch/data", es_log_dir: "/opt/elasticsearch/logs", 
    es_config: {
        cluster.name: "custom-cluster",
        discovery.zen.ping.unicast.hosts: "",
        network.host: "0.0.0.0",
        http.port: 9201,
        transport.tcp.port: 9301,
        node.data: true,
        node.master: false,
        bootstrap.memory_lock: true,
        } 
    }
